steps:
# Build Docker image: docker build -f Dockerfile -t gcr.io/my-project/my-image:latest
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'Dockerfile', '-t', 'gcr.io/layodemo/github.com/luj20/luj20:latest', '.']

# Push to GCR: gcloud docker -- push gcr.io/my-project/my-image:latest
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/layodemo/github.com/luj20/luj20:latest']
    
# Connect to GCE server and configure access for Container Registry
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['compute', 'ssh', 'techpuz8', '--zone', 'us-central1-a', '--command', 'docker-credential-gcr configure-docker']
    
# Connect to GCE server and pull new image 
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['compute', 'ssh', 'techpuz8', '--zone', 'us-central1-a', '--command', 'docker -- pull gcr.io/layodemo/github.com/luj20/luj20:latest']

# Connect to server and stop current container
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['compute', 'ssh', 'techpuz8', '--zone', 'us-central1-a',  '--command', 'docker rm $$(docker container ls -aq)']

  # Connect to server and start new container
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['compute', 'ssh', 'techpuz8', '--zone', 'us-central1-a',  '--command', 'docker run  --restart unless-stopped --name NodeJS --log-driver=gcplogs  gcr.io/layodemo/github.com/luj20/luj20:latest']
